### ISSUE TITLE
Errors when runserver

### ISSUE THREAD

**Issue by eddapp** [justdjango/django-simple-ecommerce#17]
I understand there is another repo thats updated form this one however it seems incomplete....anyway this repo has this error:

```
  from decouple import config
ModuleNotFoundError: No module named 'decouple'
```

this appears after following your instrucitons then runserver. can not migrate or runserver.

**Comment by eddapp** [comment]
solved it

**Comment by unexploredairspace** [comment]
For anyone wondering, the solution is to run `pip install python-decouple`, or the equivalent command on your Operating System.
