### ISSUE TITLE
How to configure on my system? 

### ISSUE THREAD

**Issue by bhavesh2699** [justdjango/django-simple-ecommerce#2]
Can you please update readme like which branch to clone and how to install project on our system.

**Comment by PatrykOlechno** [comment]
Branches are like step by step guide to accomplish this project. If you just want to fool around ready project go for the last branch. Clone it to your machine. Run pip install -r requirements.txt on venv, start server and you're done. If you want to learn then you can go with video https://www.youtube.com/watch?v=YZvRrldjf1Y&t=8310s, but pay attention that it uses older versions.

**Comment by bhavesh2699** [comment]
Thanks a lot @PatrykOlechno
